sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install coveralls
script:
- pycodestyle uw_bridge/
- coverage run uw_bridge/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_bridge/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_bridge/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: ewp+QUQIguGZiyiiH1RTSQf94Mr8v/xFq12q/TxppfduXEmfVYgWw/AWOmPb7HeLF0W8sqVM1k4U2m7sJz5U6+NBpC2UhrJAjw2fb3RFq2ZFgRU44eVnLBzL5OPI9yxR8n1ySFDMrR2U030Bg9E9uVSqzKTajUe8P9tk94/vN4iIlWI18QnytMANReczrOaKleFDWAxWxnRljwP/Cv7u1of+1INvStH+SmdpvMitmnNL+NLSRCzJlExEcVXlg92s9M3vIyoFsy3IaVKUYPXnkAy4ZWJ7E4qo73PFgyyFV2eYifHXHfybjKTmCr9iEaI4iBqD4dM7QH5TY2aEsBgwW+qB7JdSxqhwzABJKUqhRgyrLa2UMl1kymQbVdWicz4cyHK5/BTZVYKlLV8jhf1O0HXu8ZIG3lzpi9S8Acag3DWndh24kLGtpvXrItoMywO78PyQklxfK9+oL36ZsmKAjm8Qor0GrtbIizJpTwPEserJJXNXxEm/KXe6w6AQySqxRFp9QcDhRZ5PxwqSztSHxLYwiYjQZBE/75Pg2khq9ugBCfs5ipgYs7kfDZ5nE+HJU+4owPry8o8gMjT7pDQHK0wKZ5OYchs2/X72y2N8HolwQjwmjqvtRWJTIKQZ1XU07nuhgUvrXzPYme0McptQU2+mzBgyl7qFFKW8WacJckk=
  on:
    tags: true
    python: '3.6'
